steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      # This line required to pull correct credentials.
      # https://cloud.google.com/build/docs/build-config-file-schema#network
      - --network=cloudbuild
      - '--target=app'
      - '--tag=us-central1-docker.pkg.dev/docker-rlef-exploration/agentless-repo/agentless-image:v1p5_noemb_nodocker'
      - '.'
options:
  machineType: 'E2_HIGHCPU_32'
images:
  - 'us-central1-docker.pkg.dev/docker-rlef-exploration/agentless-repo/agentless-image:v1p5_noemb_nodocker'